#!/bin/bash

openssl genpkey -algorithm RSA -out private_key_b.pem
openssl rsa -pubout -in private_key_b.pem -out public_key_b.pem

echo "hello user" > data.txt

scp public_key_a.pem rk@192.168.1.65:/home/rk/A/

openssl dgst -sha256 -sign private_key_b.pem -out signature.bin data.txt

openssl rsautl -encrypt -pubin -inkey public_key_a.pem -in data.txt -out enc>

openssl rsautl -encrypt -pubin -inkey public_key_a.pem -in signature.bin -ou>

scp encrypted_data.bin rk@192.168.1.65:/home/rk/A/
scp encrypted_signature.bin rk@192.168.1.65:/home/rk/A/


